name: card_app
description: A new Flutter application.


publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Pacifico
      fonts:
      - asset: fonts/Pacifico-Regular.ttf
    - family: Source Sans Pro
      fonts:
      - asset: fonts/SourceSansPro-Regular.ttf
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


